version: '3.9'
services:
  dashboard:
    platform: linux/amd64
    image: 'greptime/greptimedb-dashboard:latest'
    container_name: greptime-dashboard
    volumes:
      - /home/ahmed/Desktop:/home/ahmed/Desktop
    pull_policy: always
    ports:
      - '8080:8080'
    environment:
      - GREPTIMEDB_HTTP_HOST=db
  db:
    image: 'greptimedb-htop:latest'
    container_name: greptime-db
    volumes:
      - /home/ahmed/Desktop:/home/ahmed/Desktop
    pull_policy: always
    command: 'standalone start --http-addr=0.0.0.0:4000'

# SELECT COUNT(*) AS document_count FROM temperature;
# CREATE TABLE temperature (device_id STRING, ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP() TIME INDEX, temperature DOUBLE);
# COPY public.temperature FROM '/home/ahmed/Desktop/data_platform/tmp_data_100k.json' WITH (FORMAT = 'json');

# mysql --ssl-mode=REQUIRED -u yB8kSRQhLaecLvnaL3ziBejr -p -h as7dvqzmwf8x.us-west-2.aws.greptime.cloud -P 4002 -A bnwnvr60f1tpsodium-public
# mysql pass: your-password
